# Site settings
title: "My Blogs Related to Stuff I Dive Into Over Weekends"
description: >
  This is a blog where I write about things I explore on weekends.  
  I am a software engineer, passionate about tech developments, and I document my learnings here.

# Build settings
remote_theme: "cotes2020/jekyll-theme-chirpy"
markdown: kramdown
